bounds:
  rMC_peak: !!python/tuple
  - 0.001
  - 1.
  rMC_th: !!python/tuple
  - 0.001
  - 1.
  rCM_th1: !!python/tuple
  - 0.001
  - 1.
  rCM_peak1: !!python/tuple
  - 0.001
  - 1.
  rCM_th2: !!python/tuple
  - 0.01
  - 1.
  rCM_peak2: !!python/tuple
  - 0.001
  - 1.
  rCM_min2: !!python/tuple
  - 0.01
  - 1.
  rMC0: !!python/tuple
  - 0.1
  - 10.
  rCM0: !!python/tuple
  - 0.1
  - 10.
  local_signal_rise: !!python/tuple
  - 5.
  - 200.
  local_signal_decay: !!python/tuple
  - 50.
  - 4000.
  global_signal_rise: !!python/tuple
  - 5.
  - 200.
  global_signal_decay: !!python/tuple
  - 50.
  - 3000.
  peak_delta_weight: !!python/tuple
  - 1.5
  - 4.
default_params:
rel_bounds:
- - local_signal_decay
  - '>'
  - 1.0
  - local_signal_rise
- - global_signal_decay
  - '>'
  - 1.0
  - global_signal_rise
- - local_signal_decay
  - '>'
  - 1.0
  - global_signal_decay
- - rMC_peak
  - '>'
  - 1.0
  - rMC_th
- - rCM_peak1
  - '>'
  - 1.0
  - rCM_th1
- - rCM_peak2
  - '>'
  - 1.0
  - rCM_th1
- - rCM_th2
  - '>'
  - 1.0
  - rCM_peak1
- - rCM_th2
  - '>'
  - 1.0
  - rCM_peak2
feature_names:
- spont_delta_amp
- spont_delta_width
- spont_delta_peak_shift
- spont_delta_asymmetry
- spont_delta_min_loc
- spont_delta_min_val
- exp1_delta_amp
- exp1_delta_width
- exp1_delta_peak_shift
- exp1_delta_asymmetry
- exp1_delta_min_loc
- exp1_delta_min_val
- exp2_delta_amp
- exp2_delta_width
- exp2_delta_peak_shift
- exp2_delta_asymmetry
- exp2_delta_min_loc
- exp2_delta_min_val
update_context:
- - optimize_BTSP_CA1
  - update_model_params
get_features_stages:
- source: optimize_BTSP_CA1
  get_args_static: get_args_static_signal_amplitudes
  compute_features: compute_features_signal_amplitudes
  filter_features: filter_features_signal_amplitudes
- source: optimize_BTSP_CA1
  get_args_dynamic: get_args_dynamic_model_ramp
  compute_features: compute_features_model_ramp
  filter_features: filter_features_model_ramp
get_objectives:
  optimize_BTSP_CA1: get_objectives
kwargs:
  data_file_name: '20180411_BTSP2_CA1_data.hdf5'
  verbose: 1
  min_delta_weight: -0.2
  data_keys:
objective_names:
- spont_residual_score
- exp1_residual_score
- exp2_residual_score
- self_consistent_delta_residual_score
optimization_title: bidirectional_BTSP
param_gen: PopulationAnnealing
param_names:
- rMC_peak
- rMC_th
- rCM_th1
- rCM_peak1
- rCM_th2
- rCM_peak2
- rCM_min2
- rMC0
- rCM0
- local_signal_rise
- local_signal_decay
- global_signal_rise
- global_signal_decay
- peak_delta_weight
target_range:
  ramp_offset: 0.01
  delta_min_val: 0.01
  delta_peak_val: 0.01
  residuals: 0.1
  weights_smoothness: 0.01
target_val:
x0:
  global_signal_decay: 132.717591
  local_signal_rise: 39.067314
  rMC_th: 0.273831
  rMC_peak: 0.478475
  global_signal_rise: 107.367346
  peak_delta_weight: 1.534246
  rCM_min2: 0.194243
  local_signal_decay: 64.059869
  rCM0: 1.575364
  rMC0: 5.796954
  rCM_th1: 0.347866
  rCM_th2: 0.688018
  rCM_peak1: 0.688015
  rCM_peak2: 0.503690
